custom:
  server: study

  feign:
    member: http://member:8081/api/member

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(plDde76MscNwKMt9v4A6Rw==)
    password: ENC(OH+qshDPtFh1h1gDdWExzz/t0BlOzVbo)
    url: ENC(cQUB47WfdehGJ/B1hlQxP4bpmUxFRNyGu/4MY91aS3P8AegR0zD/QPfbAOd2A5rkoG8+aIxRxkEjlzFlDmvt8EWhGC5uujEJ5+gFp6VL86BGNPkJICyY2gip6e3mk/9LoqdlLagZVrINiMAT3V32C2x67EKL8rZkch8Jc+uzhmU7Cv0vjdthuNPlASmTOFSB)

  jpa:
    hibernate:
      ddl-auto: update

#  kafka:
#    bootstrap-servers: kafka.kafka.svc.cluster.local:19092
#    consumer:
#      group-id: study
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      linger:
#        ms: 10