custom:
  mapping:
    study:
      web: /web/study
      api: /api/study
    my-study:
      web: /web/my-study

  jwt:
    secret-key: ENC(+GbV3Ykx/t5XFlaFHBZnXTzsSf9b3YChS2cVPTvCgwQmevtbB1Hfw91VMC/fTizxVssJvYiAMeQICsuoSrH5zNLh/jxJsXq/)

  feign:
    community: http://comm:8086/pub/comm/api
    member: http://localhost:8081/api/member

  db:
    url: jdbc:mysql://127.0.0.1:3306/bk__study?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    usr: ENC(MrlF9UZUaHufCgWLRE3ipQ==)
    pw: ENC(dhw6nRBS+50xHhqPVFnZdw==)

  jpa:
    ddl-auto: create

  kafka:
    server: ENC(4U1Evn0+MZzVJcTiiJ3LFNB4t8ISA5Kc)
  redis:
    host: localhost
    pw: ENC(GBrC1cw8fEgPRtmFQPTaZA==)


server:
  port: 8082

spring:
  profiles:
    default: dev

  application:
    name: study

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(EnGEuiNi8se1PXYrqy+PxI2vcLBn3DGx)
    password: ENC(cqAYQgTmw7Ze3I5X+tqACkP8Ai5vr+DCPvV9cv8n2uk=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  mvc:
    hidden-method:
      filter:
        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${custom.db.url}
    username: ${custom.db.usr}
    password: ${custom.db.pw}
    hikari:
      maximum-pool-size: 51
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: ${custom.jpa.ddl-auto}
    properties:
      hibernate:
        format_sql: true
        show_sql: true

#  kafka:
#    bootstrap-servers: ${custom.kafka.server}:9092
#    consumer:
#      group-id: study
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      linger:
#        ms: 10

#message:
#  topic:
#    studyRule: "studyRule"
#    solved-member: "solved-member"
#    name: "study"


logging.level:
  org.hibernate:
    SQL: debug
    orm.jdbc.bind: trace

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password:

---

spring:
  config:
    activate:
      on-profile: dev